name: Test SSH Key

on:
  push:
    branches:
      - master

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_YOGA_SSH_SECRET }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no yogasubagja@185.201.9.208 -p 9797 'echo "SSH key works!"'
        
      - name: List files on VPS
        run: |
          ssh -o StrictHostKeyChecking=no yogasubagja@185.201.9.208 -p 9797 'ls -la'
