name: Test SSH Key

on:
  push:
    branches:
      - dev

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_YOGA_SSH_SECRET }}
          

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} -p ${{ secrets.VPS_PORT }} 'echo "SSH key works!"'
        
      - name: List files on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} -p ${{ secrets.VPS_PORT }} 'ls -la'
