name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets. VPS_PORT }}
          key: ${{ secrets.VPS_YOGA_SSH_SECRET }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/your-app-name
            git pull origin main
            npm install --production
            npm run build
            pm2 restart all || pm2 start npm --name "your-app-name" -- run start
